
# This file is automatically generated by setup.py
short_version = '3.0.1'
version = '3.0.1'
full_version = '3.0.1.dev-Unknown'
git_revision = 'Unknown'
release = False

if not release:
    version = full_version
